# Generated by Django 4.0.3 on 2022-11-07 16:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_postgres_timestamp_without_tz


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll_time_period',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', django_postgres_timestamp_without_tz.DateTimeWithoutTZField(default='2022-11-07 11:05:44', null=True)),
                ('stop_time', django_postgres_timestamp_without_tz.DateTimeWithoutTZField(blank=True, null=True)),
                ('start_gps', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None)),
                ('stop_gps', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None)),
                ('approved', models.BooleanField(default=False)),
                ('note', models.TextField(null=True)),
            ],
            options={
                'db_table': 'payroll_time_period',
            },
        ),
        migrations.CreateModel(
            name='TimeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('pay_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'timetype',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Workspaces',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'workspaces',
            },
        ),
        migrations.CreateModel(
            name='Work_time_period',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('work_id', models.IntegerField(null=True)),
                ('start_time', django_postgres_timestamp_without_tz.DateTimeWithoutTZField(blank=True, default='2022-11-07 11:05:44')),
                ('stop_time', django_postgres_timestamp_without_tz.DateTimeWithoutTZField(blank=True, null=True)),
                ('start_gps', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('stop_gps', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('mileage', models.CharField(max_length=255, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('note', models.TextField(null=True)),
                ('timetype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worktime_period_timetype', to='trackerApi.timetype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worktime_period_user_id', to='trackerApi.users')),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_time_period', to='trackerApi.workspaces')),
            ],
            options={
                'db_table': 'work_time_period',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('payroll_time_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to='trackerApi.payroll_time_period')),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to='trackerApi.workspaces')),
            ],
            options={
                'db_table': 'work',
            },
        ),
        migrations.AddField(
            model_name='timetype',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetype', to='trackerApi.workspaces'),
        ),
        migrations.AddField(
            model_name='payroll_time_period',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payrolltime_period_user_id', to='trackerApi.users'),
        ),
        migrations.AddField(
            model_name='payroll_time_period',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_time_period', to='trackerApi.workspaces'),
        ),
        migrations.CreateModel(
            name='Gps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gps_point', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=None)),
                ('timestamp', django_postgres_timestamp_without_tz.DateTimeWithoutTZField(blank=True, default='2022-11-07 11:05:44')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps_user', to='trackerApi.users')),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps', to='trackerApi.workspaces')),
            ],
            options={
                'db_table': 'gps',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('foreman_user_id', models.IntegerField()),
                ('crew_user_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='trackerApi.workspaces')),
            ],
            options={
                'db_table': 'crew',
            },
        ),
    ]
